# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "predicted", # <qra_create_ensemble>
  "observed", # <qra_create_ensemble>
  "weight", # <qra_create_ensemble>
  "predicted", # <qra>
  "..model", # <qra>
  NULL
))
