# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "predicted", # <qra_create_ensemble>
  "observed", # <qra_create_ensemble>
  "weight", # <qra_create_ensemble>
  ".SD", # <split_forecast>
  "model", # <split_forecast>
  "included", # <split_forecast>
  "predicted", # <qra>
  "..model", # <qra>
  NULL
))
